server:
  port: 8081

workDir: "/Users/mfedechko/workspace/rsavto/folders"
inPhotosFolder: "/Users/mfedechko/workspace/rsavto/foto"

google:
  chunkSize: 200
  sleepTime: 15

upload:
  wait:
    category: 10

data:
  phoneNumber: 0638080251